### ISSUE TITLE
composer installation error

### ISSUE THREAD

**Issue by A3road** [WPBP/generator#20]
Trying to install using composer gives me the following error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wpbp/generator dev-master -> satisfiable by wpbp/generator[dev-master].
    - wpbp/generator dev-master requires mte90/clio dev-master as v0.5.3-beta -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.`

**Comment by Mte90** [comment]
Fixed with the last commit

**Comment by Mte90** [comment]
I am trying to understand why using composer is not working but cloning the repo and running composer update install everything without problems

**Comment by Mte90** [comment]
Ok now is finally working!
