### ISSUE TITLE
Newbie: what to do when running generator

### ISSUE THREAD

**Issue by clemens-tolboom** [WPBP/generator#27]
Following the [readme](https://github.com/WPBP/generator/blob/master/readme.md) I should get the list of commands when `wpbp-generator --help` but that explains the options only.

I guess I need to run `wpbp-generator --json` but in what directory?

Should the help be more specific for `--json`

>--json
     Generate a wpbp.json file in the current folder.

**Comment by Mte90** [comment]
You are right, the generator need to be in the folder where you want that the plugin folder is generated so `wp-content/plugins`.

**Comment by clemens-tolboom** [comment]
- Why don't we require this wp-content/plugins?
- This would mean we can only create a single plugin due to the location of `wpbp.json` right?

**Comment by Mte90** [comment]
The generator use the folder where the script is executed to find the `wpbp.json` file and to generate the plugin. I didn't specified about a specific folder because there is how change the path.
In any case an hint about the ideal path where execute the generator will be not bad.

**Comment by clemens-tolboom** [comment]
Thanks :)
