### ISSUE TITLE
Dark/white color switch

### ISSUE THREAD

**Issue by clemens-tolboom** [WPBP/generator#28]
I had a hard time reading the output from `generator`

![wp-generator-console-output](https://user-images.githubusercontent.com/371014/37458895-b6efed9a-2846-11e8-85e6-7877dde72628.png)

**Comment by Mte90** [comment]
The problems is that I have no idea about how to detect the color of the terminal and adapt.
So maybe we can add a flag like dark/white and set one as default to avoid this problem.

**Comment by clemens-tolboom** [comment]
I close this issue as we now have a PR #29
