### ISSUE TITLE
Grunt install fails on directories with spaces 

### ISSUE THREAD

**Issue by flegfleg** [WPBP/generator#40]
Continuing from https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/issues/142

Unfortunately, there are still errors happening: 

```
😀 Grunt install in progress
sh: line 0: cd: /Users/fleg/WorkBench/3: No such file or directory
```

**Comment by Mte90** [comment]
are you sure about the generator version are you using it?

**Comment by Mte90** [comment]
The problem was in grunt and not in composer...
I am releasing a new version.
