### ISSUE TITLE
wpdb-generator: command not found

### ISSUE THREAD

**Issue by gabriele-carbonai** [WPBP/generator#44]
After installation (in composer Folder), I try to launch the command but is not find it.
in the folder, I can not see any file .phar.
I try to install manually, by downloading .phar file but is still not work.

What can I do?
Thank you

**Comment by Mte90** [comment]
With composer you don't get any phar file.
You should have in `vendor/wpbp/generator/bin/wpbp-generator` the tool that you can execute.
Usually devs has in bash a rewrite for this case, because the `vendor/bin/` include all the binaries that you can run, also wpbp-generator is there because the package add this support.

**Comment by gabriele-carbonai** [comment]
I try in local and in remote server and in both case is not work.
inside the server, I am sure it was installed 
`- Installing wpbp/generator (dev-master ed2fed4): Cloning ed2fed4d13 from cache`
But it is supposedly working from everywhere, itsn't?

**Comment by Mte90** [comment]
Yes of course, I don't understand do you have the folder in your local vendor or you are installing global the package?

**Comment by gabriele-carbonai** [comment]
I try to install it globally.
the files are here:

`./root/.config/composer/vendor/wpbp/generator/generator/wpbp.php`

If I try to launch directly to the generator folder, still not work.

I probably did something wrong.

**Comment by Mte90** [comment]
Yes because this is not the right path.
As I wrote there https://github.com/WPBP/generator/issues/44#issuecomment-663444134 the path is not generator/generator but generator/bin the right folder.

**Comment by gabriele-carbonai** [comment]
Inside bin folder, I have wpbp-generator, in generator folder I have PHP files.
It looks like correct

**Comment by Mte90** [comment]
Yes they are all php files, you can execute the one in bin.
If you have php-cli installed in the machine you can execute it without issues.

**Comment by gabriele-carbonai** [comment]
that is ok but is not working if I try to launch 
`wpbp-generator --help`
if it is globally I can use it everywhere but still in bin folder is not work, and the file it is there

**Comment by gabriele-carbonai** [comment]
ok it is work if I launch like it
`./wpbp-generator --help`
but only in bin folder, it is not possible to have globally?

**Comment by Mte90** [comment]
As I said on https://github.com/WPBP/generator/issues/44#issuecomment-663444134 usually devs add more path where the shell can find commands to execute.
It is the same for python, nodejs etc. You need to hack the PATH variable to add more, like I do https://github.com/Mte90/dotfiles/blob/master/.bash/export.sh#L19
