### ISSUE TITLE
Update install instructions for WSL2

### ISSUE THREAD

**Issue by webdevisme** [WPBP/generator#48]
Following the instructions using composer, I had to modify the path setup in my .bashrc to 

```
export PATH=~/.config/composer/vendor/bin:$PATH
```

Running

```
wpbp-generator --help
```

Worked great then!

**Comment by Mte90** [comment]
This is part of installing composer in your machine.
Otherwise you cannot use any of the scripts installed with composer like phpstan or grumphp as example.
