### ISSUE TITLE
Composer: Conflict with your requirements or minimun-stability

### ISSUE THREAD

**Issue by nicolabavaro** [WPBP/generator#5]
When running "**composer global require wpbp/generator:dev-master**" I get this error:

./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wpbp/generator dev-master -> satisfiable by wpbp/generator[dev-master].
    - wpbp/generator dev-master requires 1happyplace/clio v0.5.1-beta -> satisfiable by 1happyplace/clio[v0.5.1-beta] but these conflict with your requirements or minimum-stability.

Installation failed, deleting ./composer.json.

**Comment by Mte90** [comment]
It is a problem of your global minimum stability.
Edit your composer.json file adding "minimum-stability":"dev" like:

```
{
    "require": {
        "wpbp/generator": "dev-master",
    },
    "minimum-stability":"dev"
}
```

**Comment by nicolabavaro** [comment]
Thanks a lot, lightning response.

**Comment by Mte90** [comment]
I have to add that in the readme XD
