### ISSUE TITLE
Plugin_Name not being renamed.

### ISSUE THREAD

**Issue by dev-jenny** [WPBP/generator#50]
Not sure if I have to manually refactor all instances of Plugin_Name in namespaces and comments, but running the generator gives me something like this even if I specify a plugin name in the json file:

```
<?php

/**
 * Plugin_Name
 *
 * @package   Plugin_Name
 * @author    {{author_name}} <{{author_email}}>
 * @copyright {{author_copyright}}
 * @license   {{author_license}}
 * @link      {{author_url}}
 */

namespace Plugin_Name\Backend;

use Plugin_Name\Engine\Base;
```

My base plugin file uses the correct plugin name that I used in wpbp.json including the correct constant prefix. 

However all other classes are like my code snippet above and constants used everywhere else use the PN prefix (presumably from Plugin_Name). For example, `PN_TEXTDOMAIN` is used throughout which leads to a PHP warning when activating the plugin: ` Use of undefined constant PN_TEXTDOMAIN`

I'm using Homestead Vagrant, PHP 7.4. The only error I get when I run the generator is `PHP Warning:  rmdir(/home/vagrant/site1/public/plugin_temp/): Text file busy in /home/vagrant/site1/public/vendor/perchten/rmrdir/src/rmrdir.php on line 17` but it continues and generates the plugin files.

**Comment by Mte90** [comment]
Can I have you wpbp.json?
It is very strange it is like the replace is not executed at all

**Comment by dev-jenny** [comment]
I just changed the plugin name and kept everything else as it is. Please see attached [wpbp.zip](https://github.com/WPBP/generator/files/7260168/wpbp.zip)

I created a new plugin named Sample just to test it again. Here's the plugin base file which is correct:
```
<?php

/**
 * @package   Sample
 * @author    Your Name <my@email.com>
 * @copyright 2020 Your Name or Company Name
 * @license   GPL 2.0+
 * @link      http://domain.tld
 *
 * Plugin Name:     Sample
 * Plugin URI:      @TODO
 * Description:     @TODO
 * Version:         1.0.0
 * Author:          Your Name
 * Author URI:      http://domain.tld
 * Text Domain:     sample
 * License:         GPL 2.0+
 * License URI:     http://www.gnu.org/licenses/gpl-2.0.txt
 * Domain Path:     /languages
 * Requires PHP:    7.0
 * WordPress-Plugin-Boilerplate-Powered: v3.2.0
 */

// If this file is called directly, abort.
if ( !defined( 'ABSPATH' ) ) {
	die( 'We\'re sorry, but you can not directly access this file.' );
}

define( 'S_VERSION', '1.0.0' );
define( 'S_TEXTDOMAIN', 'sample' );
define( 'S_NAME', 'Sample' );
define( 'S_PLUGIN_ROOT', plugin_dir_path( __FILE__ ) );
define( 'S_PLUGIN_ABSOLUTE', __FILE__ );
define( 'S_MIN_PHP_VERSION', '7.0' );
define( 'S_WP_VERSION', '5.3' );
```

Everything else though was not replaced.

**Comment by Mte90** [comment]
You are right is not replacing in the other files...
I am on that

**Comment by Mte90** [comment]
So I should be able to fix now to me is working also for others files.
I am doing a new release

**Comment by Mte90** [comment]
A new release is there with the bugfix https://github.com/WPBP/generator/releases/tag/1.1.17

Let me know if it is working to you too :-)

**Comment by dev-jenny** [comment]
Hi unfortunately it still does not work on my end. But now that I know where the replacing takes place I can give it a shot tomorrow and report back :) Thank you!

**Comment by Mte90** [comment]
It is very strange how do you installed the tool?

**Comment by dev-jenny** [comment]
Hi! I install it exactly the same way as in the tutorial. I did some troubleshooting today and it seems that running the generator the second time renames all files properly! Doing some debugging I found out that in the first run, the function `get_files()` in the `execute_generator` method only returns the root files of the plugin. So anything inside directories are not included hence not renamed. The second run gets all files properly. I am not sure what is causing this though but at least I have a fix now and anyone else that might experience it :)

**Comment by Mte90** [comment]
It is very strange as that code is there since the first release and no one reported it.
I guess that you installed wrong the tool, are you on Windows?

Did you tried the binary version that don't need composer https://github.com/WPBP/generator/releases/tag/1.1.17?
