### ISSUE TITLE
Conflict with class_exists loading? (Skyverge WooCommerce Memberships)

### ISSUE THREAD

**Issue by kevinjavitz** [WPBP/generator#51]
I am using 1.2.0 I generate the plugin with the default wpbp.json and run the composer update and put the plugin in my plugins folder. I can't load and get a php fatal error. There seems to be a conflict with class_exists type checks used on the plugin Skyverge WooCommerce Memberships, any idea how to fix?

Error: `PHP Fatal error: Cannot declare class SkyVerge\WooCommerce\PluginFramework\v5_10_6\SV_WC_API_Exception, because the name is already in use in C:\WinNMP\WWW\WPdev\wp-content\plugins\woocommerce-memberships\vendor\skyverge\wc-plugin-framework\woocommerce\api\class-sv-wc-api-exception.php on line 35`

Code from that file, I tried commenting out the class include and it just gives the same error on another file with a similar check:

````namespace SkyVerge\WooCommerce\PluginFramework\v5_10_6;

defined( 'ABSPATH' ) or exit;

if ( ! class_exists( '\\SkyVerge\\WooCommerce\\PluginFramework\\v5_10_6\\SV_WC_Plugin_Exception' ) ) :


/**
 * Plugin Framework Exception - generic Exception
 */
class SV_WC_Plugin_Exception extends \Exception { }


endif;```

**Comment by Mte90** [comment]
Hi seems that you have a class `SV_WC_API_Exception` already loaded. Your plugin have a class with the similar name?
Because this doesn't seems an issue of the boilerplate but some confusions on what are the classes loaded.
