### ISSUE TITLE
Plugin name with whitespaces does not become a slug separated by hyphens

### ISSUE THREAD

**Issue by tomonic-x** [WPBP/generator#63]
```wpbp.json
{
  "plugin": {
    "name": "Good Plugin Name"
  }
}
```

Expected WPBP_PLUGIN_SLUG is `good-plugin-name`.
Actual WPBP_PLUGIN_SLUG is `goodpluginname`.

https://github.com/WPBP/generator/blob/master/generator/init.php#L37

**Comment by Mte90** [comment]
You are right, this shouldn't happen, probably is the preg_replace in the line you mentioned that strip the whitespace so the next function is not executed.

I will work on this ASAP.

**Comment by Mte90** [comment]
So I checked the behaviour of the generator and it was always in that way.
I think that it wasn't right as usually space is always replaced with a dash.
I am releasing now a new version with the fix.
