### ISSUE TITLE
Undefined method `Page_Madness_Detector::has_entrophy()`

### ISSUE THREAD

**Issue by michael-sumner** [WPBP/generator#66]
After installation:
`wordpress/wp-content/plugins/score-detect/backend/Notices.php`
`has_entrophy()` must be `has_entropy()`

![Screenshot_2023-05-21_at_110515](https://github.com/WPBP/generator/assets/75835774/4029acae-4b90-45aa-8391-6c3f10600a86)

**Comment by Mte90** [comment]
I already fixed that issue on the boilerplate 3 weeks ago https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/backend/Notices.php#L39
The latest boilerplate release include that fix.
