### ISSUE TITLE
Generator seems to be stuck at "Composer install" phase

### ISSUE THREAD

**Issue by lincetto** [WPBP/generator#8]
Hi, using a smart new linux box, launching the generator, the process seems to be stuck at "Composer install" phase.
The problem is that Composer is asking GitHub credentials to clone repos, but the stderr output is redirected and so no message/prompt are written to the output.

`Generation done, I am superfast! You: (ʘ_ʘ)`
`😀 Composer install in progress`
`You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug`
`Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos`
`Head to https://github.com/settings/tokens/new?scopes=repo&description=xxxxxxxxx+2016-11-18+1518
to retrieve a token. It will be stored in "/home/ubuntu/.composer/auth.json" for future use by Composer.`
`Token (hidden): `

**Comment by Mte90** [comment]
It seems a problem of your installation http://artarmstrong.com/blog/2014/12/23/how-to-fix-composer-update-failure-due-to-github-authorization/
Maybe you used so much composer and github limit the connection to your host but it is not an issue of the generator.

**Comment by lincetto** [comment]
You're right, but because stderr has been redirected to stdout, the prompt for token does not appear and the script is interrupted waiting for input :

[https://github.com/WPBP/generator/blob/master/Generator/functions.php#L359](url)

My issue was not for the reason, but for the fact that the redirection does not permit to show any Composer error

**Comment by Mte90** [comment]
In any case there is the --no-download paramter to not use that feature and for the moment is impossible to have a console system where reply to that errore writing the token.
